import Head from "next/head";
import SortingVisualizer from "../components/SortingVisualizer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sorting Visualizer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SortingVisualizer />
    </div>
  );
}
